first pull request
nokiuu/Roman-Lapyuk-IPZ-32 pull request #1
Opened 2023-10-03 09:17 UTC by nokiuu

я не знаю чи правильно пулл зробив, но перевірте пж

2023-10-04 19:17 UTC, vozniuk-lntu commented
все добре, але зроби деплой гілки

2023-10-05 10:59 UTC, nokiuu commented
> все добре, але зроби деплой гілки

зробив, і додав посилання в шапку

2023-10-05 16:07 UTC, vozniuk-lntu requested changes
1. це список посилань https://i.imgur.com/DJcJAIZ.png
2. тут = має бути https://i.imgur.com/6HpSE1A.png
3. це h3 https://i.imgur.com/ekFh8zB.png
4. прописати alt для картинок
5. текст обгортаємо у відповідні теги https://i.imgur.com/gLyZN5u.png. BR не використовуємо
6. оце обгорнути в адресс тег https://i.imgur.com/bcWOaCy.png. сама адреса може бути просто абзацом, а от пошта і телефон це посилання

2023-10-05 20:02 UTC, nokiuu commented
> 1. це список посилань https://i.imgur.com/DJcJAIZ.png
> 2. тут = має бути https://i.imgur.com/6HpSE1A.png
> 3. це h3 https://i.imgur.com/ekFh8zB.png
> 4. прописати alt для картинок
> 5. текст обгортаємо у відповідні теги https://i.imgur.com/gLyZN5u.png. BR не використовуємо
> 6. оце обгорнути в адресс тег https://i.imgur.com/bcWOaCy.png. сама адреса може бути просто абзацом, а от пошта і телефон це посилання

відредагував ☺

2023-10-10 10:05 UTC, vozniuk-lntu approved these changes
1. якщо просто li написати це списком не стане https://i.imgur.com/2lkKOb1.png. Виправити
2. там де alt в розробників тобі як читалка прочитає одне слово? Репом?
3. якщо у футері ти зробив список, тоді адресу зроби теж посиланням на гугл карти, або прибери список і буде просто абзац з адресою і два посилання, а вирівнювання далі буде в CSS

це апрув, помилки виправ у наступній
зливай в мейн
перевір чи деплоїться
нову гілку з мейн робиш

2023-10-15 09:03 UTC, merged